<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contacts = [
            // Walk-in Customer
            [
                'id' => 1,
                'business_id' => 1,
                'type' => 'customer',
                'contact_type' => null,
                'supplier_business_name' => null,
                'name' => 'Walk-In Customer',
                'prefix' => null,
                'first_name' => 'Walk-In',
                'middle_name' => null,
                'last_name' => 'Customer',
                'email' => 'walkin@customer.com',
                'contact_id' => 'CO-0001',
                'contact_status' => 'active',
                'tax_number' => null,
                'city' => null,
                'state' => null,
                'country' => null,
                'address_line_1' => null,
                'address_line_2' => null,
                'zip_code' => null,
                'dob' => null,
                'mobile' => '0000000000',
                'landline' => null,
                'alternate_number' => null,
                'pay_term_number' => null,
                'pay_term_type' => null,
                'credit_limit' => null,
                'created_by' => 2,
                'converted_by' => null,
                'converted_on' => null,
                'balance' => 0.0000,
                'total_rp' => 0,
                'total_rp_used' => 0,
                'total_rp_expired' => 0,
                'is_default' => true,
                'shipping_address' => null,
                'shipping_custom_field_details' => null,
                'is_export' => false,
                'export_custom_field_1' => null,
                'export_custom_field_2' => null,
                'export_custom_field_3' => null,
                'export_custom_field_4' => null,
                'export_custom_field_5' => null,
                'export_custom_field_6' => null,
                'position' => null,
                'customer_group_id' => null,
                'crm_source' => null,
                'crm_life_stage' => null,
                'custom_field1' => null,
                'custom_field2' => null,
                'custom_field3' => null,
                'custom_field4' => null,
                'custom_field5' => null,
                'custom_field6' => null,
                'custom_field7' => null,
                'custom_field8' => null,
                'custom_field9' => null,
                'custom_field10' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Regular Customer 1
            [
                'id' => 2,
                'business_id' => 1,
                'type' => 'customer',
                'contact_type' => null,
                'supplier_business_name' => null,
                'name' => 'Alice Johnson',
                'prefix' => 'Ms.',
                'first_name' => 'Alice',
                'middle_name' => null,
                'last_name' => 'Johnson',
                'email' => 'alice.johnson@email.com',
                'contact_id' => 'CO-0002',
                'contact_status' => 'active',
                'tax_number' => null,
                'city' => 'Los Angeles',
                'state' => 'California',
                'country' => 'United States',
                'address_line_1' => '123 Main Street',
                'address_line_2' => 'Apt 4B',
                'zip_code' => '90001',
                'dob' => '1990-05-15',
                'mobile' => '+11234567890',
                'landline' => null,
                'alternate_number' => null,
                'pay_term_number' => 30,
                'pay_term_type' => 'days',
                'credit_limit' => 5000.0000,
                'created_by' => 2,
                'converted_by' => null,
                'converted_on' => null,
                'balance' => 0.0000,
                'total_rp' => 100,
                'total_rp_used' => 0,
                'total_rp_expired' => 0,
                'is_default' => false,
                'shipping_address' => '123 Main Street, Apt 4B, Los Angeles, CA 90001',
                'shipping_custom_field_details' => null,
                'is_export' => false,
                'export_custom_field_1' => null,
                'export_custom_field_2' => null,
                'export_custom_field_3' => null,
                'export_custom_field_4' => null,
                'export_custom_field_5' => null,
                'export_custom_field_6' => null,
                'position' => null,
                'customer_group_id' => null,
                'crm_source' => null,
                'crm_life_stage' => null,
                'custom_field1' => null,
                'custom_field2' => null,
                'custom_field3' => null,
                'custom_field4' => null,
                'custom_field5' => null,
                'custom_field6' => null,
                'custom_field7' => null,
                'custom_field8' => null,
                'custom_field9' => null,
                'custom_field10' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Regular Customer 2
            [
                'id' => 3,
                'business_id' => 1,
                'type' => 'customer',
                'contact_type' => null,
                'supplier_business_name' => null,
                'name' => 'Bob Smith',
                'prefix' => 'Mr.',
                'first_name' => 'Bob',
                'middle_name' => null,
                'last_name' => 'Smith',
                'email' => 'bob.smith@email.com',
                'contact_id' => 'CO-0003',
                'contact_status' => 'active',
                'tax_number' => 'TAX-BOB-001',
                'city' => 'New York',
                'state' => 'New York',
                'country' => 'United States',
                'address_line_1' => '456 Oak Avenue',
                'address_line_2' => null,
                'zip_code' => '10001',
                'dob' => '1985-08-20',
                'mobile' => '+19876543210',
                'landline' => '+12125551234',
                'alternate_number' => null,
                'pay_term_number' => 15,
                'pay_term_type' => 'days',
                'credit_limit' => 10000.0000,
                'created_by' => 2,
                'converted_by' => null,
                'converted_on' => null,
                'balance' => 0.0000,
                'total_rp' => 250,
                'total_rp_used' => 50,
                'total_rp_expired' => 0,
                'is_default' => false,
                'shipping_address' => '456 Oak Avenue, New York, NY 10001',
                'shipping_custom_field_details' => null,
                'is_export' => false,
                'export_custom_field_1' => null,
                'export_custom_field_2' => null,
                'export_custom_field_3' => null,
                'export_custom_field_4' => null,
                'export_custom_field_5' => null,
                'export_custom_field_6' => null,
                'position' => null,
                'customer_group_id' => null,
                'crm_source' => null,
                'crm_life_stage' => null,
                'custom_field1' => null,
                'custom_field2' => null,
                'custom_field3' => null,
                'custom_field4' => null,
                'custom_field5' => null,
                'custom_field6' => null,
                'custom_field7' => null,
                'custom_field8' => null,
                'custom_field9' => null,
                'custom_field10' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Supplier 1
            [
                'id' => 4,
                'business_id' => 1,
                'type' => 'supplier',
                'contact_type' => null,
                'supplier_business_name' => 'Tech Supplies Inc.',
                'name' => 'Tech Supplies Inc.',
                'prefix' => null,
                'first_name' => 'Tech',
                'middle_name' => null,
                'last_name' => 'Supplies',
                'email' => 'info@techsupplies.com',
                'contact_id' => 'CO-0004',
                'contact_status' => 'active',
                'tax_number' => 'SUP-TAX-001',
                'city' => 'San Francisco',
                'state' => 'California',
                'country' => 'United States',
                'address_line_1' => '789 Tech Park',
                'address_line_2' => 'Building A',
                'zip_code' => '94102',
                'dob' => null,
                'mobile' => '+14155551234',
                'landline' => '+14155559999',
                'alternate_number' => null,
                'pay_term_number' => 30,
                'pay_term_type' => 'days',
                'credit_limit' => null,
                'created_by' => 2,
                'converted_by' => null,
                'converted_on' => null,
                'balance' => 0.0000,
                'total_rp' => 0,
                'total_rp_used' => 0,
                'total_rp_expired' => 0,
                'is_default' => false,
                'shipping_address' => null,
                'shipping_custom_field_details' => null,
                'is_export' => false,
                'export_custom_field_1' => null,
                'export_custom_field_2' => null,
                'export_custom_field_3' => null,
                'export_custom_field_4' => null,
                'export_custom_field_5' => null,
                'export_custom_field_6' => null,
                'position' => null,
                'customer_group_id' => null,
                'crm_source' => null,
                'crm_life_stage' => null,
                'custom_field1' => null,
                'custom_field2' => null,
                'custom_field3' => null,
                'custom_field4' => null,
                'custom_field5' => null,
                'custom_field6' => null,
                'custom_field7' => null,
                'custom_field8' => null,
                'custom_field9' => null,
                'custom_field10' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Both (Customer and Supplier)
            [
                'id' => 5,
                'business_id' => 1,
                'type' => 'both',
                'contact_type' => null,
                'supplier_business_name' => 'Global Trading Co.',
                'name' => 'Global Trading Co.',
                'prefix' => null,
                'first_name' => 'Global',
                'middle_name' => null,
                'last_name' => 'Trading',
                'email' => 'contact@globaltrading.com',
                'contact_id' => 'CO-0005',
                'contact_status' => 'active',
                'tax_number' => 'BOTH-TAX-001',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'country' => 'United States',
                'address_line_1' => '321 Commerce Blvd',
                'address_line_2' => 'Suite 500',
                'zip_code' => '60601',
                'dob' => null,
                'mobile' => '+13125551234',
                'landline' => '+13125559999',
                'alternate_number' => null,
                'pay_term_number' => 45,
                'pay_term_type' => 'days',
                'credit_limit' => 25000.0000,
                'created_by' => 2,
                'converted_by' => null,
                'converted_on' => null,
                'balance' => 0.0000,
                'total_rp' => 500,
                'total_rp_used' => 100,
                'total_rp_expired' => 0,
                'is_default' => false,
                'shipping_address' => '321 Commerce Blvd, Suite 500, Chicago, IL 60601',
                'shipping_custom_field_details' => null,
                'is_export' => false,
                'export_custom_field_1' => null,
                'export_custom_field_2' => null,
                'export_custom_field_3' => null,
                'export_custom_field_4' => null,
                'export_custom_field_5' => null,
                'export_custom_field_6' => null,
                'position' => null,
                'customer_group_id' => null,
                'crm_source' => null,
                'crm_life_stage' => null,
                'custom_field1' => null,
                'custom_field2' => null,
                'custom_field3' => null,
                'custom_field4' => null,
                'custom_field5' => null,
                'custom_field6' => null,
                'custom_field7' => null,
                'custom_field8' => null,
                'custom_field9' => null,
                'custom_field10' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('contacts')->insert($contacts);
    }
}
