<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InvoiceLayoutSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('invoice_layouts')->insert([
            'id' => 1,
            'name' => 'Default Invoice Layout',
            'header_text' => null,
            'invoice_no_prefix' => 'Invoice No:',
            'quotation_no_prefix' => 'Quotation No:',
            'invoice_heading' => 'Invoice',
            'sub_heading_line1' => null,
            'sub_heading_line2' => null,
            'sub_heading_line3' => null,
            'sub_heading_line4' => null,
            'sub_heading_line5' => null,
            'invoice_heading_not_paid' => null,
            'invoice_heading_paid' => null,
            'quotation_heading' => 'Quotation',
            'sub_total_label' => 'Subtotal',
            'discount_label' => 'Discount',
            'tax_label' => 'Tax',
            'total_label' => 'Total',
            'round_off_label' => 'Round Off',
            'total_due_label' => 'Total Due',
            'paid_label' => 'Paid',
            'show_client_id' => false,
            'client_id_label' => 'Customer ID',
            'client_tax_label' => 'Tax Number',
            'date_label' => 'Date',
            'date_time_format' => null,
            'show_time' => true,
            'show_brand' => false,
            'show_sku' => true,
            'show_cat_code' => false,
            'show_expiry' => false,
            'show_lot' => false,
            'show_image' => false,
            'show_sale_description' => false,
            'sales_person_label' => 'Sales Person',
            'show_sales_person' => false,
            'table_product_label' => 'Product',
            'table_qty_label' => 'Quantity',
            'table_unit_price_label' => 'Unit Price',
            'table_subtotal_label' => 'Subtotal',
            'cat_code_label' => 'Category Code',
            'logo' => null,
            'show_logo' => true,
            'show_business_name' => true,
            'show_location_name' => true,
            'show_landmark' => false,
            'show_city' => true,
            'show_state' => true,
            'show_zip_code' => true,
            'show_country' => true,
            'show_mobile_number' => true,
            'show_alternate_number' => false,
            'show_email' => true,
            'show_tax_1' => true,
            'show_tax_2' => false,
            'show_barcode' => false,
            'show_payments' => true,
            'show_customer' => true,
            'customer_label' => 'Customer',
            'commission_agent_label' => 'Commission Agent',
            'show_commission_agent' => false,
            'show_reward_point' => false,
            'highlight_color' => '#000000',
            'footer_text' => 'Thank you for your business!',
            'module_info' => null,
            'common_settings' => null,
            'is_default' => true,
            'business_id' => 1,
            'show_letter_head' => false,
            'letter_head' => null,
            'show_qr_code' => false,
            'qr_code_fields' => null,
            'design' => 'classic',
            'cn_heading' => 'Credit Note',
            'cn_no_label' => 'CN No:',
            'cn_amount_label' => 'Credit Amount',
            'table_tax_headings' => null,
            'show_previous_bal' => false,
            'prev_bal_label' => 'Previous Balance',
            'change_return_label' => 'Change Return',
            'product_custom_fields' => null,
            'contact_custom_fields' => null,
            'location_custom_fields' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
