<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => 1,
                'name' => 'iPhone 15 Pro',
                'business_id' => 1,
                'type' => 'single',
                'unit_id' => 1, // Pieces
                'secondary_unit_id' => null,
                'sub_unit_ids' => null,
                'brand_id' => 1, // Apple
                'category_id' => 4, // Smartphones
                'sub_category_id' => null,
                'tax' => 2, // VAT 5%
                'tax_type' => 'exclusive',
                'enable_stock' => true,
                'alert_quantity' => 5.0000,
                'sku' => 'SKU-0001',
                'barcode_type' => 'C128',
                'expiry_period' => null,
                'expiry_period_type' => null,
                'enable_sr_no' => true,
                'weight' => '187g',
                'product_custom_field1' => null,
                'product_custom_field2' => null,
                'product_custom_field3' => null,
                'product_custom_field4' => null,
                'product_custom_field5' => null,
                'product_custom_field6' => null,
                'product_custom_field7' => null,
                'product_custom_field8' => null,
                'product_custom_field9' => null,
                'product_custom_field10' => null,
                'product_custom_field11' => null,
                'product_custom_field12' => null,
                'product_custom_field13' => null,
                'product_custom_field14' => null,
                'product_custom_field15' => null,
                'product_custom_field16' => null,
                'product_custom_field17' => null,
                'product_custom_field18' => null,
                'product_custom_field19' => null,
                'product_custom_field20' => null,
                'image' => null,
                'product_description' => 'Apple iPhone 15 Pro with A17 Pro chip',
                'created_by' => 2,
                'preparation_time_in_minutes' => null,
                'warranty_id' => null,
                'is_inactive' => false,
                'not_for_selling' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Samsung Galaxy S24',
                'business_id' => 1,
                'type' => 'single',
                'unit_id' => 1,
                'secondary_unit_id' => null,
                'sub_unit_ids' => null,
                'brand_id' => 2, // Samsung
                'category_id' => 4, // Smartphones
                'sub_category_id' => null,
                'tax' => 2,
                'tax_type' => 'exclusive',
                'enable_stock' => true,
                'alert_quantity' => 5.0000,
                'sku' => 'SKU-0002',
                'barcode_type' => 'C128',
                'expiry_period' => null,
                'expiry_period_type' => null,
                'enable_sr_no' => true,
                'weight' => '167g',
                'product_custom_field1' => null,
                'product_custom_field2' => null,
                'product_custom_field3' => null,
                'product_custom_field4' => null,
                'product_custom_field5' => null,
                'product_custom_field6' => null,
                'product_custom_field7' => null,
                'product_custom_field8' => null,
                'product_custom_field9' => null,
                'product_custom_field10' => null,
                'product_custom_field11' => null,
                'product_custom_field12' => null,
                'product_custom_field13' => null,
                'product_custom_field14' => null,
                'product_custom_field15' => null,
                'product_custom_field16' => null,
                'product_custom_field17' => null,
                'product_custom_field18' => null,
                'product_custom_field19' => null,
                'product_custom_field20' => null,
                'image' => null,
                'product_description' => 'Samsung Galaxy S24 Ultra',
                'created_by' => 2,
                'preparation_time_in_minutes' => null,
                'warranty_id' => null,
                'is_inactive' => false,
                'not_for_selling' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'MacBook Pro 14"',
                'business_id' => 1,
                'type' => 'single',
                'unit_id' => 1,
                'secondary_unit_id' => null,
                'sub_unit_ids' => null,
                'brand_id' => 1, // Apple
                'category_id' => 5, // Laptops
                'sub_category_id' => null,
                'tax' => 3, // VAT 10%
                'tax_type' => 'exclusive',
                'enable_stock' => true,
                'alert_quantity' => 3.0000,
                'sku' => 'SKU-0003',
                'barcode_type' => 'C128',
                'expiry_period' => null,
                'expiry_period_type' => null,
                'enable_sr_no' => true,
                'weight' => '1.6kg',
                'product_custom_field1' => null,
                'product_custom_field2' => null,
                'product_custom_field3' => null,
                'product_custom_field4' => null,
                'product_custom_field5' => null,
                'product_custom_field6' => null,
                'product_custom_field7' => null,
                'product_custom_field8' => null,
                'product_custom_field9' => null,
                'product_custom_field10' => null,
                'product_custom_field11' => null,
                'product_custom_field12' => null,
                'product_custom_field13' => null,
                'product_custom_field14' => null,
                'product_custom_field15' => null,
                'product_custom_field16' => null,
                'product_custom_field17' => null,
                'product_custom_field18' => null,
                'product_custom_field19' => null,
                'product_custom_field20' => null,
                'image' => null,
                'product_description' => 'Apple MacBook Pro 14" with M3 Pro chip',
                'created_by' => 2,
                'preparation_time_in_minutes' => null,
                'warranty_id' => null,
                'is_inactive' => false,
                'not_for_selling' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Nike Air Max',
                'business_id' => 1,
                'type' => 'single',
                'unit_id' => 1,
                'secondary_unit_id' => null,
                'sub_unit_ids' => null,
                'brand_id' => 4, // Nike
                'category_id' => 2, // Clothing
                'sub_category_id' => null,
                'tax' => 2,
                'tax_type' => 'inclusive',
                'enable_stock' => true,
                'alert_quantity' => 10.0000,
                'sku' => 'SKU-0004',
                'barcode_type' => 'C128',
                'expiry_period' => null,
                'expiry_period_type' => null,
                'enable_sr_no' => false,
                'weight' => '350g',
                'product_custom_field1' => null,
                'product_custom_field2' => null,
                'product_custom_field3' => null,
                'product_custom_field4' => null,
                'product_custom_field5' => null,
                'product_custom_field6' => null,
                'product_custom_field7' => null,
                'product_custom_field8' => null,
                'product_custom_field9' => null,
                'product_custom_field10' => null,
                'product_custom_field11' => null,
                'product_custom_field12' => null,
                'product_custom_field13' => null,
                'product_custom_field14' => null,
                'product_custom_field15' => null,
                'product_custom_field16' => null,
                'product_custom_field17' => null,
                'product_custom_field18' => null,
                'product_custom_field19' => null,
                'product_custom_field20' => null,
                'image' => null,
                'product_description' => 'Nike Air Max Running Shoes',
                'created_by' => 2,
                'preparation_time_in_minutes' => null,
                'warranty_id' => null,
                'is_inactive' => false,
                'not_for_selling' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Coca Cola 500ml',
                'business_id' => 1,
                'type' => 'single',
                'unit_id' => 1,
                'secondary_unit_id' => null,
                'sub_unit_ids' => null,
                'brand_id' => 5, // Generic
                'category_id' => 3, // Food & Beverages
                'sub_category_id' => null,
                'tax' => 1, // No Tax
                'tax_type' => 'inclusive',
                'enable_stock' => true,
                'alert_quantity' => 50.0000,
                'sku' => 'SKU-0005',
                'barcode_type' => 'C128',
                'expiry_period' => 12.00,
                'expiry_period_type' => 'months',
                'enable_sr_no' => false,
                'weight' => '500ml',
                'product_custom_field1' => null,
                'product_custom_field2' => null,
                'product_custom_field3' => null,
                'product_custom_field4' => null,
                'product_custom_field5' => null,
                'product_custom_field6' => null,
                'product_custom_field7' => null,
                'product_custom_field8' => null,
                'product_custom_field9' => null,
                'product_custom_field10' => null,
                'product_custom_field11' => null,
                'product_custom_field12' => null,
                'product_custom_field13' => null,
                'product_custom_field14' => null,
                'product_custom_field15' => null,
                'product_custom_field16' => null,
                'product_custom_field17' => null,
                'product_custom_field18' => null,
                'product_custom_field19' => null,
                'product_custom_field20' => null,
                'image' => null,
                'product_description' => 'Coca Cola Classic 500ml Bottle',
                'created_by' => 2,
                'preparation_time_in_minutes' => null,
                'warranty_id' => null,
                'is_inactive' => false,
                'not_for_selling' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);

        // Product Variations (for single products, this is a dummy record)
        $productVariations = [
            ['id' => 1, 'variation_template_id' => null, 'name' => 'DUMMY', 'product_id' => 1, 'is_dummy' => true, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'variation_template_id' => null, 'name' => 'DUMMY', 'product_id' => 2, 'is_dummy' => true, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'variation_template_id' => null, 'name' => 'DUMMY', 'product_id' => 3, 'is_dummy' => true, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'variation_template_id' => null, 'name' => 'DUMMY', 'product_id' => 4, 'is_dummy' => true, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'variation_template_id' => null, 'name' => 'DUMMY', 'product_id' => 5, 'is_dummy' => true, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('product_variations')->insert($productVariations);

        // Variations (actual price data)
        $variations = [
            [
                'id' => 1,
                'name' => 'DUMMY',
                'product_id' => 1,
                'sub_sku' => 'SKU-0001',
                'product_variation_id' => 1,
                'variation_value_id' => null,
                'default_purchase_price' => 899.0000,
                'dpp_inc_tax' => 943.9500, // 899 + 5% tax
                'profit_percent' => 25.0000,
                'default_sell_price' => 1123.7500, // 899 * 1.25
                'sell_price_inc_tax' => 1179.9375, // 1123.75 * 1.05
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'combo_variations' => null,
            ],
            [
                'id' => 2,
                'name' => 'DUMMY',
                'product_id' => 2,
                'sub_sku' => 'SKU-0002',
                'product_variation_id' => 2,
                'variation_value_id' => null,
                'default_purchase_price' => 749.0000,
                'dpp_inc_tax' => 786.4500,
                'profit_percent' => 25.0000,
                'default_sell_price' => 936.2500,
                'sell_price_inc_tax' => 983.0625,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'combo_variations' => null,
            ],
            [
                'id' => 3,
                'name' => 'DUMMY',
                'product_id' => 3,
                'sub_sku' => 'SKU-0003',
                'product_variation_id' => 3,
                'variation_value_id' => null,
                'default_purchase_price' => 1599.0000,
                'dpp_inc_tax' => 1758.9000, // 1599 + 10% tax
                'profit_percent' => 20.0000,
                'default_sell_price' => 1918.8000,
                'sell_price_inc_tax' => 2110.6800,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'combo_variations' => null,
            ],
            [
                'id' => 4,
                'name' => 'DUMMY',
                'product_id' => 4,
                'sub_sku' => 'SKU-0004',
                'product_variation_id' => 4,
                'variation_value_id' => null,
                'default_purchase_price' => 80.0000,
                'dpp_inc_tax' => 84.0000,
                'profit_percent' => 50.0000,
                'default_sell_price' => 120.0000,
                'sell_price_inc_tax' => 126.0000,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'combo_variations' => null,
            ],
            [
                'id' => 5,
                'name' => 'DUMMY',
                'product_id' => 5,
                'sub_sku' => 'SKU-0005',
                'product_variation_id' => 5,
                'variation_value_id' => null,
                'default_purchase_price' => 0.8000,
                'dpp_inc_tax' => 0.8000, // No tax
                'profit_percent' => 87.5000,
                'default_sell_price' => 1.5000,
                'sell_price_inc_tax' => 1.5000,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
                'combo_variations' => null,
            ],
        ];

        DB::table('variations')->insert($variations);

        // Product Locations (link products to locations)
        $productLocations = [
            ['product_id' => 1, 'location_id' => 1],
            ['product_id' => 2, 'location_id' => 1],
            ['product_id' => 3, 'location_id' => 1],
            ['product_id' => 4, 'location_id' => 1],
            ['product_id' => 5, 'location_id' => 1],
        ];

        DB::table('product_locations')->insert($productLocations);
    }
}
